[package]
name = "cqrs-demo"
version = "0.3.0"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2021"
license = "Apache-2.0"
keywords = ["cqrs", "event-sourcing", "serverless"]
description = "A demo application for cqrs-es crate."
documentation = "https://docs.rs/cqrs-demo"
repository = "https://github.com/serverlesstechnology/cqrs-demo"
readme = "README.md"

[dependencies]
cqrs-es = "0.3.0"
postgres-es = "0.3.0"

async-trait = "0.1.52"
axum = "0.4.4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
sqlx = { version = "0.5.11", features = [ "postgres" , "runtime-tokio-rustls", "json"] }
chrono = "0.4.19"
tokio = { version = "1", features = ["full"] }
tower = "0.4.8"
tower-http = "0.2.3"

