[package]
name = "cqrs-demo"
version = "0.2.2"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"

[dependencies]

cqrs-es = "0.2.2"
persist-es = "0.2.2"
postgres-es = "0.2.2"

async-trait = "0.1.51"
serde = { version = "1.0.130", features = ["derive"]}
serde_json = "1.0"
sqlx = { version = "0.5.7", features = [ "postgres" , "runtime-tokio-rustls", "json"] }
chrono = "0.4.19"
tokio = { version = "1", features = ["full"] }
warp = "0.3.1"
