[package]
name = "cqrs-demo"
version = "0.1.0"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"

[dependencies]
cqrs-es = "0.0.17"
postgres-es = "0.0.17"

serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
iron = "0.6.1"
router = "*"
postgres = {version = "0.15.2", features = ["with-serde_json"]}
postgres-shared = "0.4.2"