[package]
name = "cqrs-demo"
version = "0.1.0"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"

[dependencies]

cqrs-es = {version="0.2.0", path="../cqrs"}
postgres-es = {version="0.2.0", path="../postgres-es"}
#cqrs-es = "0.2.0"
#postgres-es = "0.2.0"

async-trait = "0.1.51"
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
sqlx = { version = "0.5.7", features = [ "postgres" , "runtime-tokio-rustls", "json"] }
chrono = "0.4.11"
tokio = { version = "1", features = ["full"] }
warp = "0.3"