[package]
name = "cqrs-demo"
version = "0.2.5"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2021"

[dependencies]
cqrs-es = "0.2.6"
postgres-es = "0.2.6"

async-trait = "0.1.52"
axum = "0.4.4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
sqlx = { version = "0.5.10", features = [ "postgres" , "runtime-tokio-rustls", "json"] }
chrono = "0.4.19"
tokio = { version = "1", features = ["full"] }
tower = "0.4.8"
tower-http = "0.2.3"

[patch.crates-io]
cqrs-es = {path = "../cqrs"}
postgres-es = {path = "../postgres-es"}